BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-java17-image"
BBFILE_PATTERN_meta-java17-image = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-java17-image = "7"

LAYERDEPENDS_meta-java17-image = "core meta-openjdk-temurin"
LAYERSERIES_COMPAT_meta-java17-image = "scarthgap"